#!/usr/bin/env bash
# displays numbers from 1 to 100.

for item in {1..100}; do
    if [ $((item % 3)) -eq 0 ] && [ $((item % 5)) -eq 0 ]; then
        echo FizzBuzz
    elif [ $((item % 3)) -eq 0 ]; then
        echo Fizz
    elif [ $((item % 5)) -eq 0 ]; then
        echo Buzz
    else
        echo "$item"
    fi
done
